name: usercraft
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  # state management
  provider: ^6.1.5

  # network
  dio: ^4.0.0
  pretty_dio_logger: ^1.2.0-beta-1

  # animation
  easy_splash_screen: ^1.0.4
  flutter_easyloading: ^3.0.5
  fluttertoast: ^8.2.12

  # network image
  cached_network_image: ^3.4.1

  # ui
  persistent_bottom_nav_bar: ^6.2.1

  # launcher icons
  flutter_launcher_icons: ^0.14.3


flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
  adaptative_icon_background: "#000000"
  adaptative_icon_foreground: "assets/icon/icon.png"


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
  - assets/images/
  - assets/icon/